### ISSUE TITLE
SilverStripe 4 support?

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-html5#14]
Is this module needed in SilverStripe 4 or have we incorporated its features into core?

**Comment by robbieaverill** [comment]
My assumption is that with a newer set of required browsers SS4 shouldn't need this module

**Comment by dhensby** [comment]
related: https://github.com/silverstripe/silverstripe-framework/issues/7310

**Comment by robbieaverill** [comment]
Also related https://github.com/silverstripe/silverstripe-framework/issues/7341

**Comment by robbieaverill** [comment]
cc @be2n

**Comment by robbieaverill** [comment]
For now we will upgrade it, and maybe replace the parser with something supported today if we have time

**Comment by robbieaverill** [comment]
Resolved in #17
