### ISSUE TITLE
HTML5 conflict with silverstripe-SVG/Elemental

### ISSUE THREAD

**Issue by jules0x** [silverstripe/silverstripe-html5#15]
I've found a bug where you're unable to copy a page to a Subsite when the content field is empty, eg. I'm using Elemental elements for content instead of the standard content field.

```
ERROR [User Error]: Uncaught Exception: Object->__call(): the method 'getelementsbytagname' does not exist on 'SS_HTML5Value', or the method is not public.
IN POST /admin/pages/edit/EditForm/93?Locale=en_NZ
Line 780 in /Users/jules0x/Sites/projectX/framework/core/Object.php

Source
======
  771: 
  772:                 default :
  773:                     throw new Exception (
  774:                         "Object->__call(): extra method $method is invalid on $class:"
  775:                             . var_export($config, true)
  776:                     );
  777:             }
  778:         } else {
  779:             // Please do not change the exception code number below.
* 780:             throw new Exception("Object->__call(): the method '$method' does not exist on '$class', or the
       method is not public.", 2175);
  781:         }
  782:     }
  783: 
  784:     //
       --------------------------------------------------------------------------------------------------------------
  785: 
  786:     /**

Trace
=====
Object->__call(getElementsByTagName,Array)
HTMLValue.php:122

SS_HTMLValue->__call(getElementsByTagName,Array)
SiteTreeLinkTracking.php:195

SS_HTML5Value->getElementsByTagName(a)
SiteTreeLinkTracking.php:195

SiteTreeLinkTracking_Parser->process(SS_HTML5Value)
SiteTreeLinkTracking.php:58

SiteTreeLinkTracking->trackLinksInField(Content)
SiteTreeLinkTracking.php:171

SiteTreeLinkTracking->augmentSyncLinkTracking(,,,,,,)
Object.php:1063

Object->extend(augmentSyncLinkTracking)
SiteTree.php:1551

SiteTree->syncLinkTracking()
SiteTree.php:1534

SiteTree->onBeforeWrite()
DataObject.php:1221

DataObject->preWrite()
DataObject.php:1373

DataObject->write()
SiteTreeSubsites.php:245

SiteTreeSubsites->duplicateToSubsite(1,)
```

**Comment by robbieaverill** [comment]
Thanks for reporting @jules0x. Do you have a way of reproducing this?

I've added a subsites unit test which should fail if exhibiting this behaviour, but it's passing:

```php
public function testCopyToSubsiteWithEmptyContent()
{
	// Page has no content
	$page = $this->objFromFixture('Page', 'mainSubsitePage');
	$otherSubsite = $this->objFromFixture('Subsite', 'subsite1');

	// Should fail if bug exists
	$newPage = $page->duplicateToSubsite($otherSubsite->ID);

	$this->assertNotEquals($newPage->ID, $page->ID);
}
```

**Comment by jules0x** [comment]
@robbieaverill I checked on how Elemental treats the content field, and found it stores the output of all the elements in the ElementArea as HTML in the Content field. This makes it easy to index with Solr.

So the content field is not actually empty, I'm just not using it directly as Elemental removes it from the CMS and programatically adds the cumulative markup from all the Elemental elements there instead.

What I think I have tracked down is, with Elemental I get to render each element with it's own template, so the data that is stored in the Content field contains everything the templates do. 
In this case one of my Elemental elements used a template that included a use of the silverStripe-SVG module (ie. $SVG('icon')).

This meant the Content field included the SVG, which seems to be where this particular bug occurred. 
Checking on the page I was trying to copy to the subsite, I found I couldn't publish the page in situ either. 

Removing the HTML5 module resolves the error, as does removing the $SVG('icon') call from the template.

Bit of a combination effect huh.

**Comment by robbieaverill** [comment]
Great, thanks for the detailed information @jules0x!

So in summary, this module breaks when parsing SVG data in templates - would that be correct?

**Comment by jules0x** [comment]
Yup nearly. The behaviour of Elemental is to store the rendered template in the content field, and when an SVG is present in the rendered content, then this error occurs.

**Comment by NightJar** [comment]
At a glance, this does not appear to be because of SubSites, only manifested on this copying action.

The core class of `SS_HTML4Value` defines a `__call` method that falls back to the member field storing a [`DOMDocument`](http://php.net/DOMDocument) and utilises it's member functions. However because `HTML5Value` does not use this backend, the interface is different and the abstract class makes an incorrect assumption about the methods that exist.

The most labour intensive way around this would be to implement the same interface that `DOMDocument` does, however this isn't really ideal. A better solution would be to update the API to support multiple backends (e.g. making the abstract class an interface), but that would require a major version bump to core as it's quite the change.

Perhaps someone from the core team might like to weigh in here with opinions and perhaps alternate solutions? I've not thought about this too deeply. @tractorcow @chillu

**Comment by robbieaverill** [comment]
>The behaviour of Elemental is to store the rendered template in the content field, and when an SVG is present in the rendered content, then this error occurs.

Elemental doesn't do this any more, so I'm going to assume this won't be a problem any more.

Feel free to reopen if you're still experiencing this on elemental 3.x =)
