### ISSUE TITLE
Replace parser with something modern and supported

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-html5#16]
E.g. https://github.com/Masterminds/html5-php

Related issue: https://github.com/silverstripe/silverstripe-framework/issues/7310

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-html5/pull/18

**Comment by robbieaverill** [comment]
We're reverting #18 via #22 and #24 because the two other parsers we've tried aren't working completely. I'll leave this issue open for future work, but note that at time of writing both of these parsers aren't ready for this module:

* ivopetkov/html5-dom-document-php: 0.4.16
* masterminds/html5: ^2.3

**Comment by NightJar** [comment]
An extra note as to why the ivopetkov module is such an old version (current release is 0.5.8) is because the 0.5 line is PHP 7 only, and we still support PHP 5.6.

**Comment by GuySartorelli** [comment]
Silverstripe no longer supports PHP 5.6 - may be worth someone taking a look at this again.

**Comment by GuySartorelli** [comment]
This is no longer a supported module, and HTML 5 support comes out of the box for framework in CMS 5. Closing this issue.
