### ISSUE TITLE
Generation of unneeded closing tags: <br></br>, <img></img>, ...

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-html5#19]
Version 2.0.0 works fine on my local web server, but when I deploy it, it generates closing tags for e.g. `<br>` and `<img>`. I'm assuming it's because of a php module that is active over there and not on my local installation. Feel free to suggest how I should debug that.

**Comment by robbieaverill** [comment]
Interesting. Could you start by posting a Gist of phpinfo on both local and production?

**Comment by JorisDebonnet** [comment]
~Here's a gist with both phpinfos~ [edit: deleted now]. (not sure whether I could have made the html 'rendered', I guess you'll need to copy-paste)
Let me know when you have them, then I'll delete the gist :)

Neither have tidy enabled; that's the first thing I thought of.

**Comment by robbieaverill** [comment]
Sure, you can delete now

**Comment by JorisDebonnet** [comment]
Okay, this is weird, I just copied the database from the live server to my local server, and now the unneeded closing tags occur on my local development as well. I did also remove the local silverstripe-cache at the same time, which may also have had an effect. In any case, `composer remove silverstripe/html5` solves the issue until further notice ... :)

**Comment by robbieaverill** [comment]
Thanks for following up on this. FYI this module is essentially a wrapper around https://github.com/Masterminds/html5-php. There may be some clues in issues there?

**Comment by NightJar** [comment]
@JorisDebonnet have you noticed at all if this might be related to whether or not the content includes shortcodes?

This _may_ be related to https://github.com/silverstripe/silverstripe-html5/pull/20

**Comment by JorisDebonnet** [comment]
@NightJar hm, I don't think so. I tried testing that, but when I readded silverstripe/html5, I cannot reproduce the issue now (ever after clearing silverstripe-cache)... elusive thing. I'll keep it on and see whether it reappears...

**Comment by JorisDebonnet** [comment]
Ah, apoligies, it does still appear, but only after re-publishing the page (I forgot I had to do that). My page does not have any shortcodes though, at least not in the Content or in any template I made.

**Comment by dhensby** [comment]
@JorisDebonnet links and/or images are automagically turned to shortcodes - do you have any links or files/images in the content area?

**Comment by NightJar** [comment]
Confirmed it.

_All_ self closing tags are messed up when there's a shortcode present in the content (and the option to parse is enabled). Interestingly if the shortcode is invalid then it renders fine (no `</img>`) - but all other short tags end up with a closing counterpart (`<br></br>`). However if the shortcode _is_ valid, then it's replacement content also receives an undesired and invalid friend in the form of `</img>`.

It must be links setting off the issue. The publish will be required as conversion of shortcodes happens in calling `forTemplate` - i.e. on render, rather than save or value fetching.

**Comment by NightJar** [comment]
hurr durr test the right thing @nightjar
The issues lies with `HTML5Value`, not `DBHTMLText` (which only uses the former when there are shortcodes present).

So.
`masterminds/html5`@`2.3.0` can't handle self closing tags correctly.
🤷‍♂️ 

***

Nope, can't replicate with a stand-alone install of the dependency.
Hmm. 🤔 

***

`recipe/core` with only this module installed exhibits the same issue.

**Comment by NightJar** [comment]
Resolved in #20 :)

**Comment by NightJar** [comment]
I'll close this for now - but if you check out the latest `2.x-dev` @JorisDebonnet and this issue still exists for you, feel free to re-open :)

***

Or @robbieaverill will close it while I'm typing :P

![image](https://user-images.githubusercontent.com/778003/37589662-d06d5d16-2bca-11e8-9c94-6162cffd1ca6.png)

**Comment by JorisDebonnet** [comment]
I did not actually have a shortcode in my Content, although it did have a named anchor tag (just an `<a>`-tag). In any case though, 2.x-dev has fixed the issue, so thanks!

**Comment by NightJar** [comment]
Thanks for confirming :)

**Comment by JorisDebonnet** [comment]
Ow, something weird happened.

On my homepage, I have some custom CSS in my Content field to install a background image. 
`<section class="hero" style="background-image: url(assets/1c0d50c946/before-after.jpg);">`

Since this module update however, it gets turned into this: 
`<section class="hero" style="background-image: url('html5-dom-document-internal-entity2-039-endassets/1c0d50c946/before-after.jpghtml5-dom-document-internal-entity2-039-end');">`

This conversion happens upon saving the page.

If I save it a second time, the prefix and suffix is doubled.

**Comment by NightJar** [comment]
Yep, I've just picked this up in a unit test elsewhere too.
I'm looking further into it :)
#22
